### ISSUE TITLE
JWT cookie isn't stored on production

### ISSUE THREAD

**Issue by wdsrocha** [wdsrocha/dojo#19]
DOJO uses JWT based authentication, so the login flow happens like this:

1. User sends a POST request to the API with `username` and `password` payload
2. It returns a 200 status, response payload with `username`, `email` and `userId` data. Besides that, it sets an `Authentication` HttpOnly cookie, which is the JWT
3. This cookie is set server side, so the JS have no access to it
4. JS manually sets the data from payload on the local storage, using the `@App:session` key
5. In the following requests, the `Authentication` cookie is sent in the header ✅

This is working fine locally, the `Authentication` cookie is being persisted in the browser and the user is able to navigate in authorized areas as expected. But when deployed to production, it stops working.

## Environment information

- The front-end uses the NextJS framework and is hosted at Vercel under the `dojo.run` domain.
- The back-end uses the NestJS framework and is hosted at Heroku under the `dojo-run-api.herokuapp.com` domain.

For now, CORS is being used, and I believe that the problem is a CORS misconfiguration (even though it works locally between the back-end on port `2000` and front-end on port `3000`). I want to move away from CORS for different reasons (like performance optimizations), but _for now_ I'm looking into faster to implement solutions. Of course, if it end-up being easier to just move away from CORS right now, I would prefer to do it.

CORS setup/usage:

- How the NestJS (node) server sets the CORS configuration: https://github.com/wdsrocha/dojo/blob/cors/packages/server/src/main.ts#L19-L27
- Authentication controller on back-end: https://github.com/wdsrocha/dojo/blob/cors/packages/server/src/authentication/authentication.controller.ts#L28-L40
- Login request on front-end: https://github.com/wdsrocha/dojo/blob/cors/packages/app/contexts/auth.tsx#L68-L98
- `fetch` configuration on front-end: https://github.com/wdsrocha/dojo/blob/cors/packages/app/utils/fetchOptions.ts

## Reproduction

_Portuguese only video_

https://user-images.githubusercontent.com/26108090/126083438-edeb339a-104e-40c3-bad5-80bcfd28b96d.mov

Or just follow these steps:
1. Go to https://dojo.run/submit/uri-1000
2. Open your devtools
3. Login using account with username `user1` and password `1234`
4. Type any text inside the `textarea`
5. Submit the problem
6. A message will pop-up saying that you aren't logged in, which shouldn't happen

## Related problems

- [Cookies doesn't work with Cross-site config. I'm using React (Next.js) and Node.js (Express)](https://stackoverflow.com/questions/62751029/cookies-doesnt-work-with-cross-site-config-im-using-react-next-js-and-node)
- [Next.js is not saving any cookie returned from django backend in browser cookie storage](https://stackoverflow.com/questions/66679823/next-js-is-not-saving-any-cookie-returned-from-django-backend-in-browser-cookie)

**Comment by armr-dev** [comment]
I just tested the application, after reading the issue, and found this:
![image](https://user-images.githubusercontent.com/19255973/126084409-9a7b0a8b-6b31-4604-92c2-716857034094.png)

Maybe you have to set a configuration for this SameSite issue? 

I haven't worked with JWT yet, but this warning maybe is related to this issue.

**Comment by wdsrocha** [comment]
@armr-dev that makes sense! I'll make this configuration explicit and test it again

**Comment by wdsrocha** [comment]
It was correct, thanks for spotting that @armr-dev!!

As said in [this article](https://success.outsystems.com/Support/Enterprise_Customers/Maintenance_and_Operations/Upcoming_changes_in_cookie_handling_in_Google_Chrome),

> From Chrome 80 onward, the default setting for cookies that don't specify the SameSite attribute will be SameSite=Lax.
>
> This means that these cookies will not be sent if the destination site does not match the domain that is being accessed in the browser. This will also force any third-party providers that require cross-domain integrations to: 1) specify the SameSite=None attribute in cookies to declare their intent, 2) Specify the cookie as Secure, and 3) use HTTPS connections.

After setting steps (1) and (2), it worked. Fixed on https://github.com/wdsrocha/dojo/commit/caade9eaca56647eac4ac717fe9c0d9db51523af

**Comment by armr-dev** [comment]
I'm glad it worked! 🙌🎉👏
