### ISSUE TITLE
Specify NodeJs version

### ISSUE THREAD

**Issue by RodrigoCMoraes** [wdsrocha/dojo#20]
When I've tried to execute it locally I got an error due NodeJs version, because [cypress needs NodeJs versions 12.x or 14.x and above](https://docs.cypress.io/guides/getting-started/installing-cypress#Node-js).

Then I think it sould be somewhere in the docs, maybe at README.md

**Comment by wdsrocha** [comment]
Thanks, I'll update it

By the way, when did this error occur? During the `yarn` command?

**Comment by RodrigoCMoraes** [comment]
Sorry to not give the proper context, but yes, it happened when I tried to execute `yarn install` in directory `/code/dojo/packages/server`
